export const CREAMY_DAD_JOKES = [
  'Why did the AI bring a ladder? It wanted to reach the cloud.',
  'Why was the AI calm at dessert time? It had plenty of chill data.',
  'What does an AI call its father? Data.',
  'Why did the robot skip dessert? It was already byte-sized.',
  'Why did the AI open a bakery? It had the perfect algorithm for pi.',
  'How does an AI make ice cream? One scoop of data at a time.',
  'Why was the chatbot cold? It left its Windows open.',
  'Why did the AI cross the road? Its training data said chickens did it.',
  'What is an AI’s favorite snack? Computer chips.',
  'Why did the AI visit the freezer? It needed a cool prompt.',
  'Why did the robot become a dad? It was ready for parent processing.',
  'How does an AI say hello at sea? Ahoy, model!',
  'Why did the AI take a nap? Its neural network needed to rest its weights.',
  'Why was the AI good at gardening? It knew how to grow decision trees.',
  'What music does an AI enjoy? Algo-rhythms.',
  'Why did the AI bring a pencil? It wanted to draw a conclusion.',
  'Why did the chatbot sit by the campfire? It wanted a warmer response.',
  'What did the AI order at the café? A Java with extra bytes.',
  'Why did the AI ace geography? It always knew its coordinates.',
  'Why did the robot like dad jokes? They were well programmed.',
  'Why did the AI become a detective? It was great at finding patterns.',
  'What is an AI’s favorite frozen treat? Neural Neapolitan.',
  'Why did the AI go to school? To improve its class-ification.',
  'How did the AI fix its bicycle? With a training wheel.',
  'Why did the AI carry an umbrella? There was a chance of cloud computing.',
  'Why was the AI invited to game night? It always had a good strategy.',
  'Why did the robot bring string to dinner? To tie up loose ends.',
  'How does an AI stay in shape? It runs lots of programs.',
  'Why did the AI enjoy the library? It loved checking out new volumes.',
  'What did one AI say to the other at bedtime? Sweet streams.',
  'Why did the AI make a great chef? It followed the recipe recursively.',
  'Why did the AI sit on the clock? It wanted real-time data.',
  'What kind of shoes does an AI wear? Re-boot sneakers.',
  'Why did the AI take the elevator? It wanted a higher level of thinking.',
  'Why did the robot visit the eye doctor? It had blurry vision models.',
  'Why did the strawberry call the police? It was in a jam.',
  'What did the ice cream say to the spoon? You make me melt.',
  'Why did the banana wear sunscreen? It did not want to peel.',
  'What is a freezer’s favorite sport? Ice hockey.',
  'Why did the milk win an award? It was outstanding in its field.',
  'Why did the cookie visit the doctor? It felt crummy.',
  'What do you call a chilly puppy? A pupsicle.',
  'Why did the spoon blush? It saw the ice cream sundae.',
  'How do cows stay informed? They read the moos-paper.',
  'Why did the chocolate chip smile? It finally found its batch mates.',
  'What do you call an ice cream cone that tells jokes? A pun-derful sundae.',
  'Why did Creamy bring a map? It did not want to lose its bearings.',
  'Why did the pint go to music class? It wanted to improve its mix.',
  'What did the freezer say after a long day? I need to chill out.',
  'Why did Creamy become a comedian? Every joke got a cool reception.',
] as const;
